### ISSUE TITLE
Questions about usage

### ISSUE THREAD

**Issue by ismailyenigul** [int128/deploy-lambda-action#167]
Hi,

I would like to test this action. But I have some questions about usage.

1. I dont see any configuration about setting AWS Region? How does this action know the AWS region of the lambda function?
2. Should we use just lambda function name as `function-name` or should we specify full arn?
3. For `Lambda function with container image` use case, 
  not sure but what happens if `{{ steps.metadata.outputs.tags }}` returns multiple tags?
  It might be good to add an example for tags in `metadata-action` parameters 

```
      # deploy
      - uses: int128/deploy-lambda-action@v1
        with:
          function-name: my-function
          image-uri: ${{ steps.metadata.outputs.tags }}
          alias-name: ${{ steps.metadata.outputs.version }}

**Comment by ext-ricardo-filho** [comment]
Not an expert on the issue here, But I think that this should be set up within your aws creds configuration. also, your ecr image uri can handle the region as well:
Here's an example: 
```yaml
deploy-lambda-function-after-created:
    name: deploy-lambda-function-after-created
    runs-on: ubuntu-latest
    needs: image-build-and-push
    steps:
    - name: configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
    - name: Create or update lambda image
      uses: int128/deploy-lambda-action@v1
      with:
        function-name: farmarcas-production-collector-webservice
        image-uri: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPO_NAME }}:latest
        alias-name: farmarcas-production-collector-webservice
```
